### ISSUE TITLE
deprecated compatibility.

### ISSUE THREAD

**Issue by rolinger** [apache/cordova-plugin-device-motion#61]
I know this plugin is now deprecated, but the last version of it was 2.0.1 - though it looks like someone was still doing a dev version 2.0.2.

My question is when it was deprecated, what were the version levels of cordova-ios and cordova-android (or cordova-cli) that this plugin was no longer needed?

My app is running significantly behind all the latest and greatest revs - so I need to determine that as of (example) android@6.3 and ios@4.5 this plugin is not needed.

As well, if the plugin is no longer needed, where is the documentation on how to call the new integrated functions (previously used by this plugin) for device motion functionality?

**Comment by rolinger** [comment]
Thanks.  Much appreciated.  My app uses webview+, which I believe is just an overlay to existing the existing.  Do the browsers that now support this work on older versions of android/ios.  My app supports Android 4.4+ and iOS 9.3+ - should the new navigator.compass work withe browsers supported for those platforms?

**Comment by janpio** [comment]
(I don't really know what this has to do with `navigator.compass`)

The replacement for this is an event `devicemotion`, here is its support table: https://caniuse.com/#search=devicemotion (Click "Show all" for older versions) The support is not 100% identical between webview and native browser, but pretty close.

**Comment by jcesarmobile** [comment]
The release script created a new 2.0.2-dev, but no work has been done after that as it's deprecated.
