### ISSUE TITLE
Apple has crippled device motion behind permission check - can this plugin be revived?

### ISSUE THREAD

**Issue by distinctdan** [apache/cordova-plugin-device-motion#69]
So as of iOS 13, Apple now requires a website or webview to ask permission before using the device motion API's for security reasons. The permission request launches a popup that the user has to agree to, which has to be done every time the app runs. For my tilt-based game, this is unacceptable. What do you guys think about reviving this plugin? Or, is there some workaround? I've been unable to find a way to permanently enable motion for a webview.

Safari release notes:
https://developer.apple.com/documentation/safari_release_notes/safari_13_release_notes#3314664

Medium article:
https://medium.com/flawless-app-stories/how-to-request-device-motion-and-orientation-permission-in-ios-13-74fc9d6cd140

Similar issue in different repo:
https://github.com/processing/p5.js/issues/4037

**Comment by distinctdan** [comment]
Update: this might be because the cordova webview is loaded over the `file://` protocol, although that's supposed to be supported. Once I get an iOS 13 device soon, I'll be able to investigate further why it's not working by default. 

Webkit bug thread:
https://bugs.webkit.org/show_bug.cgi?id=203287

**Comment by breautek** [comment]
A potential workaround is to migrate to the WkWebview...

According to the linked bug ticket, this doesn't affect wkwebview. It also explains why I haven't received complaints from my boss last week.

**Comment by distinctdan** [comment]
Yeah, I'm already using wkwebview, so theoretically it should already work. I'm getting an iOS 13 device tomorrow to test on, so I should have more details after that.

**Comment by distinctdan** [comment]
I finally got an iOS 13 device and was able to confirm that the browser doesn't allow access to the motion events unless you request permission. According to what I've read, a webview is supposed to be considered a trusted context since the native app already has access to motion data, so this looks like a webkit bug. There's already a closely related bug that I'm following here: https://bugs.webkit.org/show_bug.cgi?id=203287.

In the meantime, I've forked this plugin and have done some significant updates to it. I plan to try to use deviceMotion events, but if I don't have permission, then I'll fallback on this plugin instead of having to prompt the user.

**Comment by distinctdan** [comment]
For anyone who's interested, I've finished my fork here: https://github.com/distinctdan/cordova-plugin-device-motion.

I did some major changes including simplifying the API, making event frequency adjustable, and making js callbacks get called faster to reduce input lag. If there's any interest in merging it back to this plugin someday, I'm definitely open to making adjustments.

**Comment by breautek** [comment]
Did you determine if the `file://` protocol was indeed the cause?

I use the wkwebview but I don't require any permission prompt at all. But I am running the experimental local webserver plugin so my app isn't running on the `file://` protocol, it's being served locally over `http`, so that might be why I don't see this issue in my existing app.

**Comment by distinctdan** [comment]
@breautek Not sure. A related bug did get recently patched, where the issue turned out to be related to whether or not the WKWebview was using a WKUIDelegate. I've had so many problems trying to get html5 motion to work on iOS, I'm just going to use native motion until apple fixes their stuff.

 I wasn't aware there was a local server plugin, which is cool. I've resolved my issues for now by using native code, but there is a performance cost to doing a lot of plugin calls per second to send the motion data, so not having to do that by would be ideal. If I ever revisit this, I may give it a try.

**Comment by breautek** [comment]
The local webserver plugin isn't ideal either. I wouldn't recommend it unless if it's your last resort, especially if you utilise web storage in anyway.

**Comment by shinz4u** [comment]
What is the current preferred method in getting the device motion nowadays with Ionic.
Do we still use https://www.w3.org/TR/orientation-event/#worked-example or can we use @distinctdan plugin?

Or is there a workaround? 

Can this plugin or the w3 orientation-event be used when the app is in the background?

**Comment by distinctdan** [comment]
For background events, I can say that this plugin is designed to turn off while in the background. Apple doesn't allow background motion from everything I've read. https://stackoverflow.com/questions/21380806/receive-accelerometer-updates-in-background-using-coremotion-framework

**Comment by timbru31** [comment]
Plugin has been officially revived and we are resuming development. Please note, that we can't give any ETA when a new version will be available on npm. Testing, code reviews and other contributions are of course highly appreciated.

**Comment by enricodente** [comment]
Great news @timbru31 !

Consider taking a look @distinctdan fork ( https://github.com/distinctdan/cordova-plugin-device-motion ) as he implemented not long ago many improvements over the older official version.

One question: AFAIK this plugin provides acceleration only. Is there any plan to monitor gyroscope/IMU as output data compensated for drifts and gravity vector already? I think this is already a data provided by the system with no need of processing by the plugin.

**Comment by gelinger777** [comment]
I was using this plugin in my ionic app. Now it does not work on iOS . What is the actual status of the things? What should we do so that it works?
