### ISSUE TITLE
Dependencies not specified

### ISSUE THREAD

**Issue by Mani-VD** [apache/cordova-plugin-device-motion#77]
# Bug Report

### What is expected to happen?
Seamless install

### What does actually happen?
Stop with error saying module missing

## Information
 This error occurs
Installing "cordova-plugin-device-motion" for android
Failed to install 'cordova-plugin-device-motion': Error: Unable to load Platform API from /media/mani-pc/your disk1/developer folder/android project/ionic_testing/platforms/android/cordova/Api.js:
Cannot find module 'strip-final-newline'
Require stack:
- /media/mani-pc/your disk1/developer folder/android project/ionic_testing/platforms/android/cordova/node_modules/execa/index.js
- /media/mani-pc/your disk1/developer folder/android project/ionic_testing/platforms/android/cordova/lib/check_reqs.js
- /media/mani-pc/your disk1/developer folder/android project/ionic_testing/platforms/android/cordova/lib/prepare.js
- /media/mani-pc/your disk1/developer folder/android project/ionic_testing/platforms/android/cordova/Api.js
- /usr/local/lib/node_modules/cordova/node_modules/cordova-lib/src/cordova/util.js
- /usr/local/lib/node_modules/cordova/node_modules/cordova-lib/src/platforms/index.js
- /usr/local/lib/node_modules/cordova/node_modules/cordova-lib/src/platforms/platforms.js
- /usr/local/lib/node_modules/cordova/node_modules/cordova-lib/src/plugman/install.js
- /usr/local/lib/node_modules/cordova/node_modules/cordova-lib/src/plugman/plugman.js
- /usr/local/lib/node_modules/cordova/node_modules/cordova-lib/cordova-lib.js
- /usr/local/lib/node_modules/cordova/src/help.js
- /usr/local/lib/node_modules/cordova/src/cli.js
- /usr/local/lib/node_modules/cordova/bin/cordova
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:793:17)
    at Function.Module._load (internal/modules/cjs/loader.js:686:27)
    at Module.require (internal/modules/cjs/loader.js:848:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/media/mani-pc/your disk1/developer folder/android project/ionic_testing/platforms/android/cordova/node_modules/execa/index.js:5:27)
    at Module._compile (internal/modules/cjs/loader.js:955:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:991:10)
    at Module.load (internal/modules/cjs/loader.js:811:32)
    at Function.Module._load (internal/modules/cjs/loader.js:723:14)
    at Module.require (internal/modules/cjs/loader.js:848:19)
Unable to load Platform API from /media/mani-pc/your disk1/developer folder/android project/ionic_testing/platforms/android/cordova/Api.js:
Cannot find module 'strip-final-newline'
Require stack:
- /media/mani-pc/your disk1/developer folder/android project/ionic_testing/platforms/android/cordova/node_modules/execa/index.js
- /media/mani-pc/your disk1/developer folder/android project/ionic_testing/platforms/android/cordova/lib/check_reqs.js
- /media/mani-pc/your disk1/developer folder/android project/ionic_testing/platforms/android/cordova/lib/prepare.js
- /media/mani-pc/your disk1/developer folder/android project/ionic_testing/platforms/android/cordova/Api.js
- /usr/local/lib/node_modules/cordova/node_modules/cordova-lib/src/cordova/util.js
- /usr/local/lib/node_modules/cordova/node_modules/cordova-lib/src/platforms/index.js
- /usr/local/lib/node_modules/cordova/node_modules/cordova-lib/src/platforms/platforms.js
- /usr/local/lib/node_modules/cordova/node_modules/cordova-lib/src/plugman/install.js
- /usr/local/lib/node_modules/cordova/node_modules/cordova-lib/src/plugman/plugman.js
- /usr/local/lib/node_modules/cordova/node_modules/cordova-lib/cordova-lib.js
- /usr/local/lib/node_modules/cordova/src/help.js
- /usr/local/lib/node_modules/cordova/src/cli.js
- /usr/local/lib/node_modules/cordova/bin/cordova

### Command or Code
ionic cordova plugin add cordova-plugin-device-motion

### Environment, Platform, Device
android

### Version information
Ionic 6.14

## Checklist

- [ ] I searched for existing GitHub issues
- [ ] I updated all Cordova tooling to most recent version
- [ ] I included all the necessary information above

**Comment by jcesarmobile** [comment]
I can't reproduce on latest cordova
